### ISSUE TITLE
the problem with the initialization BeautifyScrollbar

### ISSUE THREAD

**Issue by dormadekhin-denis** [dwqs/v2-table#8]
the page displays several tables, some of them are hidden and initially, there is no data in them, after switching to the tab, the data is loaded but the scroll bar does not appear

**Comment by dwqs** [comment]
Thanks your feedback and i will fix it as soon as possible

**Comment by dormadekhin-denis** [comment]
Thank you for the work done! I wish you further development)

**Comment by dwqs** [comment]
Can you show me the code? :sweat_smile:

**Comment by dwqs** [comment]
Do you use `v-show` directive to control the tab display or hide? If yes，replace `v-show` with `v-if` can fix this.  Because of BeautifyScrollbar initialized once at `mounted` method，if you use `v-show`，the height of this container element which is returned by `getBoundingClientRect()` can be 0.  BeautifyScrollbar initialization will be a failure. See [beautify-scrollbar](https://github.com/dwqs/beautify-scrollbar)

**Comment by dormadekhin-denis** [comment]
Hi, sorry for the long silence. Yes, I use the `v-show`, but it is used for the block which wraps the 2 tables. Try to change the  `v-if` and see what happens.

**Comment by dwqs** [comment]
It's ok, look forward to your further feedback

**Comment by dwqs** [comment]
Long time to response
